export type Language = 'en' | 'uk';

export const translations = {
  en: {
    titleBlue: "Odesa",
    titleYellow: "Play",
    tagline: "PLAY FOR ODESA.",
    prompt: "Play while you wait!",
    play: "Play",
    playNow: "Tap a game to play and win prizes!",
    tapToPlay: "Tap to Play",
    notice: "SHOW TO WAITER",
    expires: "Expires in",
    close: "DONE",
    games: "GAME",
    me: "ME",
    quit: "Quit",
    quitConfirm: "Quit Game?",
    quitConfirmMsg: "All progress will be lost.",
    rotatePortrait: "Rotate Device",
    rotateLandscape: "Rotate Device",
    cancel: "Cancel",
    yesQuit: "Yes, Quit",
    profile: "Profile",
    profileTab: "Profile",
    statsTab: "Stats",
    settingsTab: "Settings",
    rank: "Rank: Odesa Guardian",
    gamesPlayed: "Games Played",
    cityHunt: "City Hunt",

    chooseHero: "Choose Hero Emoji",
    nicknamePlaceholder: "Username",
    cityNickname: "City Nickname",
    saveProfile: "Save Profile",
    nameTooShort: "Name too short",
    nameTaken: "Name already taken!",
    managerHub: "Manager Hub",
    live: "Live",
    settings: "Settings",
    livePlayers: "Live Players",
    prizes: "Prizes",
    standardPrizes: "Standard Prizes",
    redemptionStats: "Redemption Stats",
    noRedemptions: "No redemptions yet",
    todayHunt: "Today's Hunt",
    noRedeemedPrizes: "No redeemed prizes yet",
    activeWins: "Active Wins",
    code: "CODE",
    verify: "Give",
    noWinners: "No active winners...",
    tierSettings: "TIER SETTINGS",
    level: "Tier",
    prize: "Prize",
    pts: "pts",
    rankLabel: "Rank",
    savePrizes: "SAVE PRIZES",
    points: "Points",
    scoreBased: "Score",
    percentileBased: "Top %",
    mode: "Mode",
    saveConfig: "SAVE CONFIG",

    leaderboard: "HEROS",
    highScores: "High Scores",
    noEntries: "No players yet",
    you: "YOU",
    score: "Score: ",
    share: "Share",
    shareMessage: "Play a fun Odesa game! {url}",
    shareText: "I scored {score} in {game}! Play OdesaPlay now!",
    scanToPlay: "Share with friends",
    checkedIn: "Checked in at",
    contactText: "Contact us for custom apps or to help bring your business into the ai era.",
    timeAgoDay: "{n} day ago",
    timeAgoDays: "{n} days ago",
    timeAgoHour: "{n} hour ago",
    timeAgoHours: "{n} hours ago",
    timeAgoMin: "{n} min ago",
    timeAgoMins: "{n} mins ago",
    timeAgoJustNow: "Just now",
    recruits: "Recruits",

    progress: "Progress",
    demoMode: "Demo Mode",

    betaBanner: "Beta Mode",
    comingSoonBanner: "Coming Soon",
    onboardingTitle: "Welcome to OdesaPlay!",
    onboardingPlay: "Tap any game to play, earn XP, unlock badges, and win prizes!",
    onboardingCTA: "Let's Go!",
    splashLoading: "Loading...",
    notifyOff: "Notify me",
    notifyOn: "Notified",
    restaurants: "RESTAURANTS",
    musicSettings: "MUSIC SETTINGS",
    notifications: "NOTIFICATIONS",
    droneAlerts: "Drone Alerts",
    droneAlertsDesc: "Get notified when air raid sirens sound",
    gameReminders: "Game Reminders",
    gameRemindersDesc: "Remind me to play if idle for 2+ days",
    venueSpecials: "Venue Specials",
    venueSpecialsDesc: "Special offers from checked-in venues",
    tournamentLaunches: "Tournament Launches",
    tournamentLaunchesDesc: "Get notified when venues launch tournaments",
    autoPlayMusic: "Auto-play music",
    music: {
      anthem: "National Anthem",
      hava: "Hava Nagila",
      seven: "7:40",
      odessa: "Odesa Mama",
      stefania: "Stefania",
      verka: "Dancing Lasha Tumbai",
      nich: "Nich Yaka Misyachna",
      nichStrings: "Nich Strings",
    },
    badges: "Badges",
    noBadges: "Play games to earn badges!",
    items: "Items",
    itemsPlaceholder: "Items you collect in-game will appear here",
    activeItems: "Active Items",
    tapBadge: "Tap a badge to learn more",
    badgeUnlockedAgo: "Awarded {d} day ago",
    badgeUnlockedAgoPlural: "Awarded {d} days ago",
    badgeNotUnlocked: "Not yet unlocked",
    eggs: "Easter Eggs",
    eggsNone: "Eggs appear after updates. Keep playing!",
    eggFoundToast: "found! Check your profile.",
    /* Theme & Language UI */
    themeLanguage: "Language",
    themeLanguageInverse: "Мова",
    themeTheme: "Theme",
    themeDark: "Dark",
    themeLight: "Light",
    themeOdesa: "Odesa",
    themeUkraine: "Ukraine",
    themeUkr: "Укр",
    themeEng: "Eng",
    langUkrainian: "Українська",
    langEnglish: "Англійська",
    themeProfileNote: "Change anytime in your Profile page",
    /* Check-in Prompt */
    checkinPromptTitle: "Are you at a venue?",
    checkinPromptSub: "Check in to earn 15 XP and track your city hunt!",
    checkinConfirm: "Check In",
    checkinSkip: "Not now",
    checkinLocating: "Finding your location...",
    checkinGpsOff: "Location off",
    checkinXpEarned: "Checked in! +15 ⭐",
    connectionError: "Connection issue. Try again.",
    streak: "Streak",
    day: "day",
    days: "days",
    playerLevel: "Level",
    xp: "XP",
    xpToNext: "XP to next level",
    starsToNext: "⭐ to next level",
    stars: "⭐ Stars",
    shop: "Market",
    buy: "Get",
    sell: "Return",
    sellInfo: "Items lose 2% value per week (min 25% recoup)",
    paid: "Paid",
    recoup: "Recoup",
    weeksOwned: "{w} week owned",
    weeksOwnedPlural: "{w} weeks owned",
    soldToast: "Sold! +{v}⭐",
    notEnoughStars: "Not enough ⭐",
    confirmBuy: "Purchase {name} for {cost} ⭐?",
    slideFingerDown: "Slide finger down",
    boostActivated: "+{n}km/h {fire}",
    achievements: "Achievements",
    badgeUnlocked: "Badge Unlocked!",
    allTime: "All Time",
    thisWeek: "This Week",
    lastWeek: "Last Week",
    personalBest: "Personal Best",
    starHolders: "Top Star Holders",
    badge: {
      firstBlood: { name: "First Blood", desc: "Play your first game" },
      sharpshooter: { name: "Sharpshooter", desc: "Reach top 3 on any leaderboard" },
      globetrotter: { name: "Globetrotter", desc: "Check in at 5+ venues" },
      recruiter: { name: "Recruiter", desc: "Refer 3+ friends" },
      marshrutkaRider: { name: "Marshrutka Rider", desc: "Score 50+ in Marshrutka" },
      droneSpotter: { name: "Drone Spotter", desc: "Score 50+ in Drones" },
      lighthouseKeeper: { name: "Lighthouse Keeper", desc: "Score 100+ in Lighthouse" },
      triviaMaster: { name: "Trivia Master", desc: "Score 80%+ on Trivia" },
      streakMaster: { name: "Streak Master", desc: "Play 7 days in a row" },
      odesaNative: { name: "Odesa Native", desc: "Unlock all venue check-ins" },
      comebackKid: { name: "Comeback Kid", desc: "Beat your high score by 50%+" },
      doubleThreat: { name: "Double Threat", desc: "High score in 2+ games" },
      hatTrick: { name: "Hat Trick", desc: "High score in 3+ games" },
      dedicated: { name: "Dedicated", desc: "Play 25 games" },
      century: { name: "Century", desc: "Play 100 games" },
      odessaAddict: { name: "Odesa Addict", desc: "Play 500 games" },
      regular: { name: "Regular", desc: "Check in at 10+ venues" },
      loyalPatron: { name: "Loyal Patron", desc: "Check in at 25+ venues" },
      odessaRoyalty: { name: "Odesa Royalty", desc: "Check in at 50+ venues" },
      buddy: { name: "Buddy", desc: "Refer 1 friend" },
      networker: { name: "Networker", desc: "Refer 5+ friends" },
      superstar: { name: "Superstar", desc: "Refer 15+ friends" },
      onARoll: { name: "On a Roll", desc: "3-day streak" },
      unstoppable: { name: "Unstoppable", desc: "14-day streak" },
      eternal: { name: "Eternal", desc: "30-day streak" },
      droneAce: { name: "Drone Ace", desc: "Score 1000+ in Drones" },
      droneGod: { name: "Drone God", desc: "Score 2000+ in Drones" },
      marshrutkaChamp: { name: "Marshrutka Champ", desc: "Score 1000+ in Marshrutka" },
      marshrutkaLegend: { name: "Marshrutka Legend", desc: "Score 2000+ in Marshrutka" },
      lighthouseGuardian: { name: "Lighthouse Guardian", desc: "Score 500+ in Lighthouse" },
      lighthouseTitan: { name: "Lighthouse Titan", desc: "Score 1000+ in Lighthouse" },
      triviaScholar: { name: "Trivia Scholar", desc: "Score 90%+ on Trivia" },
      perfectScore: { name: "Perfect Score", desc: "Score 100% on Trivia" },
      silentGuardian: { name: "Silent Guardian", desc: "Perfect game in Sharpshooter" },
      peaceMaker: { name: "Peace Maker", desc: "Score 80+ in Sharpshooter" },
      risingStar: { name: "Rising Star", desc: "Reach #1 in any game" },
      quadThreat: { name: "Quad Threat", desc: "Reach #1 in 4+ games" },
      grandSlam: { name: "Grand Slam", desc: "Reach #1 in all 5 games" },
      jackOfAllTrades: { name: "Jack of All Trades", desc: "Play all 5 games" },
      darkHorse: { name: "Dark Horse", desc: "Beat your high score by 100%+" },
      partyAnimal: { name: "Party Animal", desc: "Play on 30+ different days" },
      nightOwl: { name: "Night Owl", desc: "Check in at 3+ venues in one day" },
    },
    weekStats: "Last Week's Stats",
    weekPlayers: "Players last week",
    weekHighScore: "Highest score",
    weekAvgScore: "Average score",
    weekTotalGames: "Games played",

    /* Venue Admin */
    dashboard: "Dashboard",
    venues: "Venues",
    addVenue: "Add Venue",
    editVenue: "Edit Venue",
    venueName: "Name",
    venueNameUk: "Name (UA)",
    shortCode: "Short Code",
    venueAddress: "Address",
    venueAddressUk: "Address (UA)",
    venueLat: "Latitude",
    venueLng: "Longitude",
    status: "Status",
    active: "Active",
    disabled: "Disabled",
    disableVenue: "Disable",
    enableVenue: "Enable",
    noVenues: "No venues yet",
    qrBatches: "QR Batches",
    generateBatch: "Generate Batch",
    managerCode: "Manager Code",
    checkinCode: "Check-in Code",
    batchLabel: "Batch",
    unassigned: "Available",
    assigned: "Assigned",
    assignBatch: "Assign to Venue",
    selectVenue: "Select venue",
    noBatches: "No QR batches yet",
    batchAssigned: "Assigned to",
    qrManagerLabel: "Manager Hub QR (print 1 copy)",
    qrCheckinLabel: "Customer Check-in QR (print 3 copies)",
    printMode: "Print Mode",
    venueSaved: "Venue saved",
    batchGenerated: "Batch generated",
    batchAssignedMsg: "Batch assigned to venue",
    confirmDeleteBatch: "Delete this batch?",

    /* Admin Dashboard */
    refreshData: "Refresh Data",
    totalUsers: "Total Users",
    totalCheckins: "Total Check-ins",
    prizesClaimed: "Prizes Claimed",
    referralClicks: "Referral Clicks",
    conversion: "Conversion",
    click: "Click",
    conversions: "Conversions",
    convRate: "Conv. Rate",
    playingNow: "Playing Now",
    activePlayersNow: "Active Players Now",
    recentReferralActivity: "Recent Referral Activity",
    recentLeaderboardUpdates: "Recent Leaderboard Updates",
    retry: "Retry",
    loadingData: "Loading Global Data...",
    noActivePlayers: "No one is playing right now",
    noReferrals: "No referral activity yet",
    noScores: "No scores yet",
    viewQrCodes: "View QR codes",
    printLabel: "Print",
    saving: "Saving...",
    updateVenue: "Update Venue",
    createVenue: "Create Venue",
    backToApp: "Back to App",
    total: "total",
    salesTool: "Analytics",
    today: "Today",
    thisMonth: "This Month",

    /* Sales Tool */
    restaurantName: "Bistro 7",
    restaurantNameSubtitle: "Key metrics for {name}",
    customerSources: "Customer Sources",
    conversionFunnel: "Conversion Funnel",
    mostPlayedGames: "Most Played Games",
    crossRestaurantTraffic: "Cross-Restaurant Traffic",
    weeklyGrowth: "Weekly Growth",
    qrCheckin: "Table QR Check-in",
    treasureHuntComplete: "Treasure Hunt Completion",
    crossReferral: "Cross-Restaurant Referral",
    enteredRestaurant: "Entered Restaurant",
    scannedQR: "Scanned QR",
    playedGame: "Played a Game",
    joinedHunt: "Joined Treasure Hunt",
    claimedPrize: "Claimed Prize",
    sentXGuest: "{n} guest from {restaurant} discovered you via their treasure hunt",
    sentXGuests: "{n} guests from {restaurant} discovered you via their treasure hunt",
    totalCustomers: "Total Customers",
    weeklyGrowthRate: "Weekly Growth",
    repeatRate: "Repeat Rate",
    revenueImpact: "Revenue Impact",
    customers: "customers",
    perWeek: "per week",
    gameName: "Game",
    customersCount: "Customers",
    treasureHuntOrigin: "Treasure Hunt Origin",
    guestsCount: "Guests",
    weekLabel: "Week {n}",
    sourcesSubtitle: "How customers are finding your restaurant",
    funnelSubtitle: "From entrance to loyal customer",
    gamesSubtitle: "Which games get played most after check-in",
    crossSubtitle: "Other restaurants whose treasure hunts send you guests",
    growthSubtitle: "Track your momentum week over week",
    playCount: "play",
    playsCount: "plays",

    /* Tournament Mode */
    activeTournaments: "Active Tournaments",
    liveTournaments: "Live Tournaments",
    liveTournament: "Live Tournament",
    noActiveTournaments: "No tournaments right now",
    tournamentEndsIn: "Ends in {n}",
    tournamentEnded: "Tournament ended",
    playToWin: "Play to win",
    yourRank: "Your rank",
    winningPrize: "You'd win: {prize}",
    myPrizes: "My Prizes",
    noPrizes: "No prizes yet",
    claimCode: "Code: {code}",
    validUntil: "Valid until {time}",
    claimRedeemed: "Redeemed",
    claimPending: "Pending",
    expiresInHours: "Expires in {h}h",
    mins: "mins",
    claimExpired: "Expired",
    loadAll: "Load All",
    tournamentWonTitle: "🎉 Tournament Winner!",
    tournamentWon: "You won {prize} at {venue}!",
    tournamentLost: "Too close! {winner} won with {score} pts.",
    rankGained: "You're #{rank} — you'd win {prize}!",
    rankLost: "You dropped to #{rank}. One more game to get back in!",
    tournament: "Tournament",
    launchTournament: "Launch Tournament",
    prizeLabel: "Prize",
    topWinners: "Top Winners",
    launch1hButton: "Launch 3-Hour Tournament",
    tournamentActive: "Tournament Active",
    noActiveTournament: "No active tournament",
    tournamentLeaderboard: "Tournament Standings",
    yourPosition: "Your Position",
    placeSuffix: {
      "1": "st",
      "2": "nd",
      "3": "rd"
    }
  },
  uk: {
    titleBlue: "Odesa",
    titleYellow: "Play",
    tagline: "ГРАЙ ЗА ОДЕСУ.",
    prompt: "Грай, поки чекаєш!",
    play: "Грати",
    playNow: "Обери гру, грай та вигравай призи!",
    tapToPlay: "Торкнись, щоб грати",
    notice: "ПОКАЖІТЬ ОФІЦІАНТОВІ",
    expires: "Дійсний ще",
    close: "ГОТОВО",
    games: "ГРА",
    me: "ПРОФІЛЬ",
    quit: "Вийти",
    quitConfirm: "Вийти з гри?",
    quitConfirmMsg: "Весь прогрес буде втрачено.",
    cancel: "Скасувати",
    yesQuit: "Так, вийти",
    rotatePortrait: "Поверніть пристрій",
    rotateLandscape: "Поверніть пристрій",
    profile: "Профіль",
    profileTab: "Профіль",
    statsTab: "Статистика",
    settingsTab: "Налаштування",
    rank: "Ранг: Охоронець Одеси",
    gamesPlayed: "Зіграно ігор",
    cityHunt: "Міський Квест",

    chooseHero: "Оберіть емодзі героя",
    nicknamePlaceholder: "Ім'я користувача",
    cityNickname: "Нікнейм в місті",
    saveProfile: "Зберегти профіль",
    nameTooShort: "Ім'я занадто коротке",
    nameTaken: "Ім'я вже зайняте!",
    managerHub: "Панель менеджера",
    live: "Наживо",
    settings: "Налаштування",
    livePlayers: "Гравці онлайн",
    prizes: "Призи",
    standardPrizes: "Стандартні призи",
    redemptionStats: "Статистика",
    noRedemptions: "Поки немає виграшів",
    todayHunt: "Сьогоднішній Квест",
    noRedeemedPrizes: "Ще немає отриманих призів",
    activeWins: "Активні виграші",
    code: "КОД",
    verify: "Видати",
    noWinners: "Немає активних переможців...",
    tierSettings: "НАЛАШТУВАННЯ РІВНІВ",
    level: "Рівень",
    prize: "Приз",
    pts: "очок",
    rankLabel: "Ранг",
    savePrizes: "ЗБЕРЕГТИ ПРИЗИ",
    points: "Бали",
    scoreBased: "Очки",
    percentileBased: "Топ %",
    mode: "Режим",
    saveConfig: "ЗБЕРЕГТИ КОНФІГ",

    leaderboard: "ГЕРОЇ",
    highScores: "Рекорди",
    noEntries: "Поки немає гравців",
    you: "ВИ",
    score: "Рахунок: ",
    share: "Поділитися",
    shareMessage: "Грай у веселу гру Одеси! {url}",
    shareText: "Я набрав {score} очок у {game}! Грай в OdesaPlay зараз!",
    scanToPlay: "Поділися з друзями",
    checkedIn: "Відмітився в",
    contactText: "Зв'яжіться з нами щодо створення власних застосунків або щоб залучити ваш бізнес до ери ШІ.",
    timeAgoDay: "{n} день тому",
    timeAgoDays: "{n} днів тому",
    timeAgoHour: "{n} година тому",
    timeAgoHours: "{n} год тому",
    timeAgoMin: "{n} хвилина тому",
    timeAgoMins: "{n} хв тому",
    timeAgoJustNow: "Щойно",
    recruits: "Рекрути",

    progress: "Прогрес",
    demoMode: "Демо-режим",

    betaBanner: "Бета-режим",
    comingSoonBanner: "Скоро",
    onboardingTitle: "Ласкаво просимо до OdesaPlay!",
    onboardingPlay: "Обери гру, заробляй XP, відкривай бейджі та вигравай призи!",
    onboardingCTA: "Поїхали!",
    splashLoading: "Завантаження...",
    notifyOff: "Сповістити",
    notifyOn: "Підписано",
    restaurants: "РЕСТОРАНИ",
    musicSettings: "НАЛАШТУВАННЯ МУЗИКИ",
    notifications: "СПОВІЩЕННЯ",
    droneAlerts: "Тривога",
    droneAlertsDesc: "Сповіщення про повітряну тривогу",
    gameReminders: "Нагадування",
    gameRemindersDesc: "Нагадати грати після 2+ днів бездіяльності",
    venueSpecials: "Акції закладів",
    venueSpecialsDesc: "Спеціальні пропозиції від відвіданих закладів",
    tournamentLaunches: "Турніри",
    tournamentLaunchesDesc: "Сповіщення про запуск турнірів у закладах",
    autoPlayMusic: "Автовідтворення музики",
    music: {
      anthem: "Національний гімн",
      hava: "Гава Нагіла",
      seven: "7:40",
      odessa: "Одеса Мама",
      stefania: "Стефанія",
      verka: "Танці Лаша Тумбай",
      nich: "Ніч яка місячна",
      nichStrings: "Ніч (Струнні)",
    },
    badges: "Бейджі",
    noBadges: "Грайте в ігри, щоб отримати бейджі!",
    items: "Предмети",
    itemsPlaceholder: "Предмети, які ви збираєте в грі, з'являться тут",
    activeItems: "Активні предмети",
    tapBadge: "Натисніть на бейдж, щоб дізнатися більше",
    badgeUnlockedAgo: "Отримано {d} день тому",
    badgeUnlockedAgoPlural: "Отримано {d} днів тому",
    badgeNotUnlocked: "Ще не розблоковано",
    eggs: "Великодні яйця",
    eggsNone: "Яйця з'являються після оновлень. Продовжуйте грати!",
    eggFoundToast: "знайдено! Перевір профіль.",
    /* Theme & Language UI */
    themeLanguage: "Мова",
    themeLanguageInverse: "Language",
    themeTheme: "Тема",
    themeDark: "Темна",
    themeLight: "Світла",
    themeOdesa: "Одеса",
    themeUkraine: "Україна",
    themeUkr: "Укр",
    themeEng: "Eng",
    langUkrainian: "Ukrainian",
    langEnglish: "English",
    themeProfileNote: "Можна змінити в Профілі",
    /* Check-in Prompt */
    checkinPromptTitle: "Ти в закладі?",
    checkinPromptSub: "Відміться, щоб отримати 15 XP та відстежувати свій квест!",
    checkinConfirm: "Відмітитись",
    checkinSkip: "Не зараз",
    checkinLocating: "Визначаємо ваше місцезнаходження...",
    checkinGpsOff: "Геолокація вимкнена",
    checkinXpEarned: "Відмітився! +15 ⭐",
    connectionError: "Проблема з'єднання. Спробуйте ще раз.",
    streak: "Серія",
    day: "день",
    days: "днів",
    playerLevel: "Рівень",
    xp: "XP",
    xpToNext: "XP до наступного рівня",
    starsToNext: "⭐ до наступного рівня",
    stars: "⭐ Зірки",
    shop: "Ринок",
    buy: "Отримати",
    sell: "Повернути",
    sellInfo: "Предмети втрачають 2% вартості щотижня (мін. 25%)",
    paid: "Сплачено",
    recoup: "Повернення",
    weeksOwned: "{w} тиждень",
    weeksOwnedPlural: "{w} тижнів",
    soldToast: "Продано! +{v}⭐",
    notEnoughStars: "Недостатньо ⭐",
    confirmBuy: "Купити {name} за {cost} ⭐?",
    slideFingerDown: "Опусти палець",
    boostActivated: "+{n}км/год {fire}",
    achievements: "Досягнення",
    badgeUnlocked: "Бейдж розблоковано!",
    allTime: "За весь час",
    thisWeek: "Цього тижня",
    lastWeek: "Минулого тижня",
    personalBest: "Особистий рекорд",
    badge: {
      firstBlood: { name: "Перша кров", desc: "Зіграйте свою першу гру" },
      sharpshooter: { name: "Снайпер", desc: "Потрапіть у топ-3 будь-якого лідерборду" },
      globetrotter: { name: "Мандрівник", desc: "Відміться у 5+ закладах" },
      recruiter: { name: "Рекрутер", desc: "Запросіть 3+ друзів" },
      marshrutkaRider: { name: "Пасажир маршрутки", desc: "Наберіть 50+ у Маршрутці" },
      droneSpotter: { name: "Спостерігач дронів", desc: "Наберіть 50+ у Дронах" },
      lighthouseKeeper: { name: "Доглядач маяка", desc: "Наберіть 100+ у Маяку" },
      triviaMaster: { name: "Майстер вікторини", desc: "Наберіть 80%+ у Вікторині" },
      streakMaster: { name: "Майстер серії", desc: "Грайте 7 днів поспіль" },
      odesaNative: { name: "Корінний одесит", desc: "Відмітьтеся у всіх закладах" },
      comebackKid: { name: "Камбек", desc: "Покращте свій рекорд на 50%+" },
      doubleThreat: { name: "Подвійна загроза", desc: "Рекорд у 2+ іграх" },
      hatTrick: { name: "Хет-трик", desc: "Рекорд у 3+ іграх" },
      dedicated: { name: "Відданий", desc: "Зіграйте 25 ігор" },
      century: { name: "Сотня", desc: "Зіграйте 100 ігор" },
      odessaAddict: { name: "Одеський адикт", desc: "Зіграйте 500 ігор" },
      regular: { name: "Завсідник", desc: "Відмітьтеся у 10+ закладах" },
      loyalPatron: { name: "Вірний гість", desc: "Відмітьтеся у 25+ закладах" },
      odessaRoyalty: { name: "Одеська королівська особа", desc: "Відмітьтеся у 50+ закладах" },
      buddy: { name: "Друг", desc: "Запросіть 1 друга" },
      networker: { name: "Мережевик", desc: "Запросіть 5+ друзів" },
      superstar: { name: "Суперзірка", desc: "Запросіть 15+ друзів" },
      onARoll: { name: "На хвилі", desc: "Серія 3 дні" },
      unstoppable: { name: "Невпинний", desc: "Серія 14 днів" },
      eternal: { name: "Вічний", desc: "Серія 30 днів" },
      droneAce: { name: "Ас дронів", desc: "Наберіть 1000+ у Дронах" },
      droneGod: { name: "Бог дронів", desc: "Наберіть 2000+ у Дронах" },
      marshrutkaChamp: { name: "Чемпіон маршрутки", desc: "Наберіть 1000+ у Маршрутці" },
      marshrutkaLegend: { name: "Легенда маршрутки", desc: "Наберіть 2000+ у Маршрутці" },
      lighthouseGuardian: { name: "Вартовий маяка", desc: "Наберіть 500+ у Маяку" },
      lighthouseTitan: { name: "Титан маяка", desc: "Наберіть 1000+ у Маяку" },
      triviaScholar: { name: "Знавець", desc: "Наберіть 90%+ у Вікторині" },
      perfectScore: { name: "Ідеальний рахунок", desc: "Наберіть 100% у Вікторині" },
      silentGuardian: { name: "Тихий вартовий", desc: "Ідеальна гра у Стрільці" },
      peaceMaker: { name: "Миротворець", desc: "Наберіть 80+ у Стрільці" },
      risingStar: { name: "Висхідна зірка", desc: "Досягніть #1 у будь-якій грі" },
      quadThreat: { name: "Чотири загрози", desc: "Досягніть #1 у 4+ іграх" },
      grandSlam: { name: "Великий шолом", desc: "Досягніть #1 у всіх 5 іграх" },
      jackOfAllTrades: { name: "Майстер на всі руки", desc: "Зіграйте у всі 5 ігор" },
      darkHorse: { name: "Темна конячка", desc: "Покращте рекорд на 100%+" },
      partyAnimal: { name: "Тусівник", desc: "Грайте у 30+ різних днів" },
      nightOwl: { name: "Нічна сова", desc: "Відмітьтеся у 3+ закладах за один день" },
    },
    weekStats: "Статистика за тиждень",
    weekPlayers: "Гравців за тиждень",
    weekHighScore: "Найвищий рахунок",
    weekAvgScore: "Середній рахунок",
    weekTotalGames: "Ігор зіграно",
    starHolders: "Топ зірок",

    /* Venue Admin */
    dashboard: "Дашборд",
    venues: "Заклади",
    addVenue: "Додати заклад",
    editVenue: "Редагувати",
    venueName: "Назва (EN)",
    venueNameUk: "Назва (UA)",
    shortCode: "Короткий код",
    venueAddress: "Адреса (EN)",
    venueAddressUk: "Адреса (UA)",
    venueLat: "Широта",
    venueLng: "Довгота",
    status: "Статус",
    active: "Активний",
    disabled: "Вимкнено",
    disableVenue: "Вимкнути",
    enableVenue: "Увімкнути",
    noVenues: "Поки немає закладів",
    qrBatches: "QR-набори",
    generateBatch: "Створити набір",
    managerCode: "Код менеджера",
    checkinCode: "Код відвідувача",
    batchLabel: "Набір",
    unassigned: "Доступний",
    assigned: "Призначено",
    assignBatch: "Призначити закладу",
    selectVenue: "Виберіть заклад",
    noBatches: "Ще немає QR-наборів",
    batchAssigned: "Призначено",
    qrManagerLabel: "QR менеджера (друк: 1 шт)",
    qrCheckinLabel: "QR відвідувача (друк: 3 шт)",
    printMode: "Друк",
    venueSaved: "Заклад збережено",
    batchGenerated: "Набір створено",
    batchAssignedMsg: "Набір призначено закладу",
    confirmDeleteBatch: "Видалити цей набір?",

    /* Admin Dashboard */
    refreshData: "Оновити дані",
    totalUsers: "Усього користувачів",
    totalCheckins: "Усього відміток",
    prizesClaimed: "Отримано призів",
    referralClicks: "Реферальних кліків",
    conversion: "Конверсія",
    click: "Клік",
    conversions: "Конверсій",
    convRate: "Конв. Rate",
    playingNow: "Грають зараз",
    activePlayersNow: "Активні гравці зараз",
    recentReferralActivity: "Остання реферальна активність",
    recentLeaderboardUpdates: "Останні оновлення лідерборду",
    retry: "Повторити",
    loadingData: "Завантаження даних...",
    noActivePlayers: "Ніхто не грає зараз",
    noReferrals: "Поки немає реферальної активності",
    noScores: "Поки немає результатів",
    viewQrCodes: "Переглянути QR-коди",
    printLabel: "Друк",
    saving: "Збереження...",
    updateVenue: "Оновити заклад",
    createVenue: "Створити заклад",
    backToApp: "Назад до додатку",
    total: "всього",
    salesTool: "Аналітика",
    today: "Сьогодні",
    thisMonth: "Цього місяця",

    /* Sales Tool */
    restaurantName: "Бістро 7",
    restaurantNameSubtitle: "Ключові показники для {name}",
    customerSources: "Джерела клієнтів",
    conversionFunnel: "Воронка конверсії",
    mostPlayedGames: "Найпопулярніші ігри",
    crossRestaurantTraffic: "Міжресторанний трафік",
    weeklyGrowth: "Тижневе зростання",
    qrCheckin: "QR-відмітка за столиком",
    treasureHuntComplete: "Проходження квесту",
    crossReferral: "Реферали з інших ресторанів",
    enteredRestaurant: "Зайшли в ресторан",
    scannedQR: "Сканували QR",
    playedGame: "Зіграли в гру",
    joinedHunt: "Приєднались до квесту",
    claimedPrize: "Отримали приз",
    sentXGuest: "{n} гість з {restaurant} відкрив вас через їхній квест",
    sentXGuests: "{n} гостей з {restaurant} відкрили вас через їхній квест",
    totalCustomers: "Усього клієнтів",
    weeklyGrowthRate: "Тижневе зростання",
    repeatRate: "Повторні відвідування",
    revenueImpact: "Вплив на дохід",
    customers: "клієнтів",
    perWeek: "на тиждень",
    gameName: "Гра",
    customersCount: "Клієнти",
    treasureHuntOrigin: "Джерело квесту",
    guestsCount: "Гості",
    weekLabel: "Тиждень {n}",
    sourcesSubtitle: "Як клієнти знаходять ваш ресторан",
    funnelSubtitle: "Від входу до постійного клієнта",
    gamesSubtitle: "В які ігри найчастіше грають після відмітки",
    crossSubtitle: "Ресторани, чиї квести надсилають вам гостей",
    growthSubtitle: "Відстежуйте свою динаміку тиждень за тижнем",
    playCount: "гра",
    playsCount: "ігор",

    /* Tournament Mode */
    activeTournaments: "Активні турніри",
    liveTournaments: "Живі турніри",
    liveTournament: "Живий турнір",
    noActiveTournaments: "Зараз турнірів немає",
    tournamentEndsIn: "Закінчується через {n}",
    tournamentEnded: "Турнір завершено",
    playToWin: "Грай, щоб виграти",
    yourRank: "Твій рейтинг",
    winningPrize: "Ти виграєш: {prize}",
    myPrizes: "Мої призи",
    noPrizes: "Поки немає призів",
    claimCode: "Код: {code}",
    validUntil: "Дійсний до {time}",
    claimRedeemed: "Отримано",
    claimPending: "Очікує",
    expiresInHours: "Закінч. через {h}год",
    mins: "хв",
    claimExpired: "Прострочено",
    loadAll: "Завантажити все",
    tournamentWonTitle: "🎉 Переможець турніру!",
    tournamentWon: "Ти виграв {prize} у {venue}!",
    tournamentLost: "Майже! {winner} переміг з {score} очками.",
    rankGained: "Ти #{rank} — виграєш {prize}!",
    rankLost: "Ти опустився на #{rank}. Ще одна гра, щоб повернутися!",
    tournament: "Турнір",
    launchTournament: "Запустити турнір",
    prizeLabel: "Приз",
    topWinners: "Переможців",
    launch1hButton: "Запустити турнір на 3 години",
    tournamentActive: "Турнір активний",
    noActiveTournament: "Немає активного турніру",
    tournamentLeaderboard: "Таблиця турніру",
    yourPosition: "Твоя позиція",
    placeSuffix: {
      "1": "-ше",
      "2": "-ге",
      "3": "-тє"
    }
  }
};
