export type Language = 'en' | 'uk';

export const translations = {
  en: {
    titleBlue: "Odesa",
    titleYellow: "Play",
    tagline: "PLAY FOR ODESA.",
    prompt: "Play while you wait!",
    notice: "SHOW TO WAITER",
    expires: "Expires in",
    close: "DONE",
    games: "GAME",
    me: "ME",
    quit: "Quit",
    quitConfirm: "Quit Game?",
    quitConfirmMsg: "All progress will be lost.",
    rotatePortrait: "Rotate Device",
    rotatePortraitDesc: "Please rotate your phone to portrait mode to play this game.",
    rotateLandscape: "Rotate Device",
    rotateLandscapeDesc: "Please rotate your phone to landscape mode to play this game.",
    cancel: "Cancel",
    yesQuit: "Yes, Quit",
    profile: "Profile",
    rank: "Rank: Odesa Guardian",
    gamesPlayed: "Games Played",
    cityHunt: "City Hunt",

    chooseHero: "Choose Hero Emoji",
    nicknamePlaceholder: "Username",
    cityNickname: "City Nickname",
    saveProfile: "Save Profile",
    nameTooShort: "Name too short",
    nameTaken: "Name already taken!",
    managerHub: "Manager Hub",
    live: "Live",
    settings: "Settings",
    livePlayers: "Live Players",
    prizes: "Prizes",
    standardPrizes: "Standard Prizes",
    redemptionStats: "Redemption Stats",
    noRedemptions: "No redemptions yet",
    todayHunt: "Today's Hunt",
    noRedeemedPrizes: "No redeemed prizes yet",
    activeWins: "Active Wins",
    code: "CODE",
    verify: "Give",
    noWinners: "No active winners...",
    tierSettings: "TIER SETTINGS",
    level: "Tier",
    prize: "Prize",
    pts: "pts",
    savePrizes: "SAVE PRIZES",
    points: "Points",
    scoreBased: "Score",
    percentileBased: "Top %",
    mode: "Mode",
    saveConfig: "SAVE CONFIG",

    leaderboard: "HEROS",
    highScores: "High Scores",
    noEntries: "No players yet",
    you: "YOU",
    score: "Score: ",
    share: "Share",
    shareMessage: "Play a fun Odesa game! {url}",
    shareText: "I scored {score} in {game}! Play OdesaPlay now!",
    scanToPlay: "Share with friends",
    checkedIn: "Checked in at",
    contactText: "Contact us for custom apps or to help bring your business into the ai era.",
    timeAgoDay: "{n} day ago",
    timeAgoDays: "{n} days ago",
    timeAgoHour: "{n} hour ago",
    timeAgoHours: "{n} hours ago",
    timeAgoMin: "{n} min ago",
    timeAgoMins: "{n} mins ago",
    timeAgoJustNow: "Just now",
    recruits: "Recruits",

    progress: "Progress",
    demoMode: "Demo Mode",

    betaBanner: "Beta Mode",
    comingSoonBanner: "Coming Soon",
    restaurants: "RESTAURANTS",
    musicSettings: "MUSIC SETTINGS",
    notifications: "NOTIFICATIONS",
    droneAlerts: "Drone Alerts",
    droneAlertsDesc: "Get notified when air raid sirens sound",
    gameReminders: "Game Reminders",
    gameRemindersDesc: "Remind me to play if idle for 2+ days",
    venueSpecials: "Venue Specials",
    venueSpecialsDesc: "Special offers from checked-in venues",
    tournamentLaunches: "Tournament Launches",
    tournamentLaunchesDesc: "Get notified when venues launch tournaments",
    autoPlayMusic: "Auto-play music",
    music: {
      anthem: "National Anthem",
      hava: "Hava Nagila",
      seven: "7:40",
      odessa: "Odesa Mama",
      stefania: "Stefania",
      verka: "Dancing Lasha Tumbai",
      nich: "Nich Yaka Misyachna",
      nichStrings: "Nich Strings",
    },
    badges: "Badges",
    noBadges: "Play games to earn badges!",
    /* Theme & Language UI */
    themeLanguage: "Language",
    themeLanguageInverse: "Мова",
    themeTheme: "Theme",
    themeDark: "Dark",
    themeLight: "Light",
    themeOdesa: "Odesa",
    themeUkraine: "Ukraine",
    themeUkr: "Укр",
    themeEng: "Eng",
    langUkrainian: "Українська",
    langEnglish: "English",
    themeProfileNote: "These settings can also be found at the bottom of the Profile page",
    streak: "Streak",
    day: "day",
    days: "days",
    playerLevel: "Level",
    xp: "XP",
    xpToNext: "XP to next level",
    achievements: "Achievements",
    badgeUnlocked: "Badge Unlocked!",
    allTime: "All Time",
    thisWeek: "This Week",
    lastWeek: "Last Week",
    personalBest: "Personal Best",
    badge: {
      firstBlood: { name: "First Blood", desc: "Play your first game" },
      sharpshooter: { name: "Sharpshooter", desc: "Reach top 3 on any leaderboard" },
      globetrotter: { name: "Globetrotter", desc: "Check in at 5+ venues" },
      recruiter: { name: "Recruiter", desc: "Refer 3+ friends" },
      marshrutkaRider: { name: "Marshrutka Rider", desc: "Score 50+ in Marshrutka" },
      droneSpotter: { name: "Drone Spotter", desc: "Score 50+ in Drones" },
      triviaMaster: { name: "Trivia Master", desc: "Score 80%+ on Trivia" },
      streakMaster: { name: "Streak Master", desc: "Play 7 days in a row" },
      odesaNative: { name: "Odesa Native", desc: "Unlock all venue check-ins" },
      comebackKid: { name: "Comeback Kid", desc: "Beat your high score by 50%+" },
      doubleThreat: { name: "Double Threat", desc: "High score in 2+ games" },
      hatTrick: { name: "Hat Trick", desc: "High score in 3+ games" },
    },
    weekStats: "Last Week's Stats",
    weekPlayers: "Players last week",
    weekHighScore: "Highest score",
    weekAvgScore: "Average score",
    weekTotalGames: "Games played",

    /* Venue Admin */
    dashboard: "Dashboard",
    venues: "Venues",
    addVenue: "Add Venue",
    editVenue: "Edit Venue",
    venueName: "Name",
    venueNameUk: "Name (UA)",
    shortCode: "Short Code",
    venueAddress: "Address",
    venueAddressUk: "Address (UA)",
    venueLat: "Latitude",
    venueLng: "Longitude",
    status: "Status",
    active: "Active",
    disabled: "Disabled",
    disableVenue: "Disable",
    enableVenue: "Enable",
    noVenues: "No venues yet",
    qrBatches: "QR Batches",
    generateBatch: "Generate Batch",
    managerCode: "Manager Code",
    checkinCode: "Check-in Code",
    batchLabel: "Batch",
    unassigned: "Available",
    assigned: "Assigned",
    assignBatch: "Assign to Venue",
    selectVenue: "Select venue",
    noBatches: "No QR batches yet",
    batchAssigned: "Assigned to",
    qrManagerLabel: "Manager Hub QR (print 1 copy)",
    qrCheckinLabel: "Customer Check-in QR (print 3 copies)",
    printMode: "Print Mode",
    venueSaved: "Venue saved",
    batchGenerated: "Batch generated",
    batchAssignedMsg: "Batch assigned to venue",
    confirmDeleteBatch: "Delete this batch?",

    /* Admin Dashboard */
    refreshData: "Refresh Data",
    totalUsers: "Total Users",
    totalCheckins: "Total Check-ins",
    prizesClaimed: "Prizes Claimed",
    referralClicks: "Referral Clicks",
    conversion: "Conversion",
    click: "Click",
    conversions: "Conversions",
    convRate: "Conv. Rate",
    playingNow: "Playing Now",
    activePlayersNow: "Active Players Now",
    recentReferralActivity: "Recent Referral Activity",
    recentLeaderboardUpdates: "Recent Leaderboard Updates",
    retry: "Retry",
    loadingData: "Loading Global Data...",
    noActivePlayers: "No one is playing right now",
    noReferrals: "No referral activity yet",
    noScores: "No scores yet",
    viewQrCodes: "View QR codes",
    printLabel: "Print",
    saving: "Saving...",
    updateVenue: "Update Venue",
    createVenue: "Create Venue",
    backToApp: "Back to App",
    total: "total",
    salesTool: "Analytics",
    today: "Today",
    thisMonth: "This Month",

    /* Sales Tool */
    restaurantName: "Bistro 7",
    restaurantNameSubtitle: "Key metrics for {name}",
    customerSources: "Customer Sources",
    conversionFunnel: "Conversion Funnel",
    mostPlayedGames: "Most Played Games",
    crossRestaurantTraffic: "Cross-Restaurant Traffic",
    weeklyGrowth: "Weekly Growth",
    qrCheckin: "Table QR Check-in",
    treasureHuntComplete: "Treasure Hunt Completion",
    crossReferral: "Cross-Restaurant Referral",
    enteredRestaurant: "Entered Restaurant",
    scannedQR: "Scanned QR",
    playedGame: "Played a Game",
    joinedHunt: "Joined Treasure Hunt",
    claimedPrize: "Claimed Prize",
    sentXGuest: "{n} guest from {restaurant} discovered you via their treasure hunt",
    sentXGuests: "{n} guests from {restaurant} discovered you via their treasure hunt",
    totalCustomers: "Total Customers",
    weeklyGrowthRate: "Weekly Growth",
    repeatRate: "Repeat Rate",
    revenueImpact: "Revenue Impact",
    customers: "customers",
    perWeek: "per week",
    gameName: "Game",
    customersCount: "Customers",
    treasureHuntOrigin: "Treasure Hunt Origin",
    guestsCount: "Guests",
    weekLabel: "Week {n}",
    sourcesSubtitle: "How customers are finding your restaurant",
    funnelSubtitle: "From entrance to loyal customer",
    gamesSubtitle: "Which games get played most after check-in",
    crossSubtitle: "Other restaurants whose treasure hunts send you guests",
    growthSubtitle: "Track your momentum week over week",
    playCount: "play",
    playsCount: "plays",

    /* Tournament Mode */
    activeTournaments: "Active Tournaments",
    liveTournaments: "Live Tournaments",
    liveTournament: "Live Tournament",
    noActiveTournaments: "No tournaments right now",
    tournamentEndsIn: "Ends in {n}",
    tournamentEnded: "Tournament ended",
    playToWin: "Play to win",
    yourRank: "Your rank",
    winningPrize: "You'd win: {prize}",
    myPrizes: "My Prizes",
    noPrizes: "No prizes yet",
    claimCode: "Code: {code}",
    validUntil: "Valid until {time}",
    claimRedeemed: "Redeemed",
    claimPending: "Pending",
    expiresInHours: "Expires in {h}h",
    mins: "mins",
    claimExpired: "Expired",
    loadAll: "Load All",
    tournamentWonTitle: "🎉 Tournament Winner!",
    tournamentWon: "You won {prize} at {venue}!",
    tournamentLost: "Too close! {winner} won with {score} pts.",
    rankGained: "You're #{rank} — you'd win {prize}!",
    rankLost: "You dropped to #{rank}. One more game to get back in!",
    tournament: "Tournament",
    launchTournament: "Launch Tournament",
    prizeLabel: "Prize",
    topWinners: "Top Winners",
    launch1hButton: "Launch 3-Hour Tournament",
    tournamentActive: "Tournament Active",
    noActiveTournament: "No active tournament",
    tournamentLeaderboard: "Tournament Standings",
    yourPosition: "Your Position",
    placeSuffix: {
      "1": "st",
      "2": "nd",
      "3": "rd"
    }
  },
  uk: {
    titleBlue: "Odesa",
    titleYellow: "Play",
    tagline: "ГРАЙ ЗА ОДЕСУ.",
    prompt: "Грай, поки чекаєш!",
    notice: "ПОКАЖІТЬ ОФІЦІАНТОВІ",
    expires: "Дійсний ще",
    close: "ГОТОВО",
    games: "ГРА",
    me: "ПРОФІЛЬ",
    quit: "Вийти",
    quitConfirm: "Вийти з гри?",
    quitConfirmMsg: "Весь прогрес буде втрачено.",
    cancel: "Скасувати",
    yesQuit: "Так, вийти",
    rotatePortrait: "Поверніть пристрій",
    rotatePortraitDesc: "Поверніть телефон у портретний режим для цієї гри.",
    rotateLandscape: "Поверніть пристрій",
    rotateLandscapeDesc: "Поверніть телефон у ландшафтний режим для цієї гри.",
    profile: "Профіль",
    rank: "Ранг: Охоронець Одеси",
    gamesPlayed: "Зіграно ігор",
    cityHunt: "Міський Квест",

    chooseHero: "Оберіть емодзі героя",
    nicknamePlaceholder: "Ім'я користувача",
    cityNickname: "Нікнейм в місті",
    saveProfile: "Зберегти профіль",
    nameTooShort: "Ім'я занадто коротке",
    nameTaken: "Ім'я вже зайняте!",
    managerHub: "Панель менеджера",
    live: "Наживо",
    settings: "Налаштування",
    livePlayers: "Гравці онлайн",
    prizes: "Призи",
    standardPrizes: "Стандартні призи",
    redemptionStats: "Статистика",
    noRedemptions: "Поки немає виграшів",
    todayHunt: "Сьогоднішній Квест",
    noRedeemedPrizes: "Ще немає отриманих призів",
    activeWins: "Активні виграші",
    code: "КОД",
    verify: "Видати",
    noWinners: "Немає активних переможців...",
    tierSettings: "НАЛАШТУВАННЯ РІВНІВ",
    level: "Рівень",
    prize: "Приз",
    pts: "очок",
    savePrizes: "ЗБЕРЕГТИ ПРИЗИ",
    points: "Бали",
    scoreBased: "Очки",
    percentileBased: "Топ %",
    mode: "Режим",
    saveConfig: "ЗБЕРЕГТИ КОНФІГ",

    leaderboard: "ГЕРОЇ",
    highScores: "Рекорди",
    noEntries: "Поки немає гравців",
    you: "ВИ",
    score: "Рахунок: ",
    share: "Поділитися",
    shareMessage: "Грай у веселу гру Одеси! {url}",
    shareText: "Я набрав {score} очок у {game}! Грай в OdesaPlay зараз!",
    scanToPlay: "Поділися з друзями",
    checkedIn: "Відмітився в",
    contactText: "Зв'яжіться з нами щодо створення власних застосунків або щоб залучити ваш бізнес до ери ШІ.",
    timeAgoDay: "{n} день тому",
    timeAgoDays: "{n} днів тому",
    timeAgoHour: "{n} година тому",
    timeAgoHours: "{n} год тому",
    timeAgoMin: "{n} хвилина тому",
    timeAgoMins: "{n} хв тому",
    timeAgoJustNow: "Щойно",
    recruits: "Рекрути",

    progress: "Прогрес",
    demoMode: "Демо-режим",

    betaBanner: "Бета-режим",
    comingSoonBanner: "Скоро",
    restaurants: "РЕСТОРАНИ",
    musicSettings: "НАЛАШТУВАННЯ МУЗИКИ",
    notifications: "СПОВІЩЕННЯ",
    droneAlerts: "Тривога",
    droneAlertsDesc: "Сповіщення про повітряну тривогу",
    gameReminders: "Нагадування",
    gameRemindersDesc: "Нагадати грати після 2+ днів бездіяльності",
    venueSpecials: "Акції закладів",
    venueSpecialsDesc: "Спеціальні пропозиції від відвіданих закладів",
    tournamentLaunches: "Турніри",
    tournamentLaunchesDesc: "Сповіщення про запуск турнірів у закладах",
    autoPlayMusic: "Автовідтворення музики",
    music: {
      anthem: "Національний гімн",
      hava: "Гава Нагіла",
      seven: "7:40",
      odessa: "Одеса Мама",
      stefania: "Стефанія",
      verka: "Танці Лаша Тумбай",
      nich: "Ніч яка місячна",
      nichStrings: "Ніч (Струнні)",
    },
    badges: "Бейджі",
    noBadges: "Грайте в ігри, щоб отримати бейджі!",
    /* Theme & Language UI */
    themeLanguage: "Мова",
    themeLanguageInverse: "Language",
    themeTheme: "Тема",
    themeDark: "Темна",
    themeLight: "Світла",
    themeOdesa: "Одеса",
    themeUkraine: "Україна",
    themeUkr: "Укр",
    themeEng: "Eng",
    langUkrainian: "Українська",
    langEnglish: "English",
    themeProfileNote: "Ці налаштування також можна знайти внизу сторінки Профілю",
    streak: "Серія",
    day: "день",
    days: "днів",
    playerLevel: "Рівень",
    xp: "XP",
    xpToNext: "XP до наступного рівня",
    achievements: "Досягнення",
    badgeUnlocked: "Бейдж розблоковано!",
    allTime: "За весь час",
    thisWeek: "Цього тижня",
    lastWeek: "Минулого тижня",
    personalBest: "Особистий рекорд",
    badge: {
      firstBlood: { name: "Перша кров", desc: "Зіграйте свою першу гру" },
      sharpshooter: { name: "Снайпер", desc: "Потрапіть у топ-3 будь-якого лідерборду" },
      globetrotter: { name: "Мандрівник", desc: "Відміться у 5+ закладах" },
      recruiter: { name: "Рекрутер", desc: "Запросіть 3+ друзів" },
      marshrutkaRider: { name: "Пасажир маршрутки", desc: "Наберіть 50+ у Маршрутці" },
      droneSpotter: { name: "Спостерігач дронів", desc: "Наберіть 50+ у Дронах" },
      triviaMaster: { name: "Майстер вікторини", desc: "Наберіть 80%+ у Вікторині" },
      streakMaster: { name: "Майстер серії", desc: "Грайте 7 днів поспіль" },
      odesaNative: { name: "Корінний одесит", desc: "Відмітьтеся у всіх закладах" },
      comebackKid: { name: "Камбек", desc: "Покращте свій рекорд на 50%+" },
      doubleThreat: { name: "Подвійна загроза", desc: "Рекорд у 2+ іграх" },
      hatTrick: { name: "Хет-трик", desc: "Рекорд у 3+ іграх" },
    },
    weekStats: "Статистика за тиждень",
    weekPlayers: "Гравців за тиждень",
    weekHighScore: "Найвищий рахунок",
    weekAvgScore: "Середній рахунок",
    weekTotalGames: "Ігор зіграно",

    /* Venue Admin */
    dashboard: "Дашборд",
    venues: "Заклади",
    addVenue: "Додати заклад",
    editVenue: "Редагувати",
    venueName: "Назва (EN)",
    venueNameUk: "Назва (UA)",
    shortCode: "Короткий код",
    venueAddress: "Адреса (EN)",
    venueAddressUk: "Адреса (UA)",
    venueLat: "Широта",
    venueLng: "Довгота",
    status: "Статус",
    active: "Активний",
    disabled: "Вимкнено",
    disableVenue: "Вимкнути",
    enableVenue: "Увімкнути",
    noVenues: "Поки немає закладів",
    qrBatches: "QR-набори",
    generateBatch: "Створити набір",
    managerCode: "Код менеджера",
    checkinCode: "Код відвідувача",
    batchLabel: "Набір",
    unassigned: "Доступний",
    assigned: "Призначено",
    assignBatch: "Призначити закладу",
    selectVenue: "Виберіть заклад",
    noBatches: "Ще немає QR-наборів",
    batchAssigned: "Призначено",
    qrManagerLabel: "QR менеджера (друк: 1 шт)",
    qrCheckinLabel: "QR відвідувача (друк: 3 шт)",
    printMode: "Друк",
    venueSaved: "Заклад збережено",
    batchGenerated: "Набір створено",
    batchAssignedMsg: "Набір призначено закладу",
    confirmDeleteBatch: "Видалити цей набір?",

    /* Admin Dashboard */
    refreshData: "Оновити дані",
    totalUsers: "Усього користувачів",
    totalCheckins: "Усього відміток",
    prizesClaimed: "Отримано призів",
    referralClicks: "Реферальних кліків",
    conversion: "Конверсія",
    click: "Клік",
    conversions: "Конверсій",
    convRate: "Конв. Rate",
    playingNow: "Грають зараз",
    activePlayersNow: "Активні гравці зараз",
    recentReferralActivity: "Остання реферальна активність",
    recentLeaderboardUpdates: "Останні оновлення лідерборду",
    retry: "Повторити",
    loadingData: "Завантаження даних...",
    noActivePlayers: "Ніхто не грає зараз",
    noReferrals: "Поки немає реферальної активності",
    noScores: "Поки немає результатів",
    viewQrCodes: "Переглянути QR-коди",
    printLabel: "Друк",
    saving: "Збереження...",
    updateVenue: "Оновити заклад",
    createVenue: "Створити заклад",
    backToApp: "Назад до додатку",
    total: "всього",
    salesTool: "Аналітика",
    today: "Сьогодні",
    thisMonth: "Цього місяця",

    /* Sales Tool */
    restaurantName: "Бістро 7",
    restaurantNameSubtitle: "Ключові показники для {name}",
    customerSources: "Джерела клієнтів",
    conversionFunnel: "Воронка конверсії",
    mostPlayedGames: "Найпопулярніші ігри",
    crossRestaurantTraffic: "Міжресторанний трафік",
    weeklyGrowth: "Тижневе зростання",
    qrCheckin: "QR-відмітка за столиком",
    treasureHuntComplete: "Проходження квесту",
    crossReferral: "Реферали з інших ресторанів",
    enteredRestaurant: "Зайшли в ресторан",
    scannedQR: "Сканували QR",
    playedGame: "Зіграли в гру",
    joinedHunt: "Приєднались до квесту",
    claimedPrize: "Отримали приз",
    sentXGuest: "{n} гість з {restaurant} відкрив вас через їхній квест",
    sentXGuests: "{n} гостей з {restaurant} відкрили вас через їхній квест",
    totalCustomers: "Усього клієнтів",
    weeklyGrowthRate: "Тижневе зростання",
    repeatRate: "Повторні відвідування",
    revenueImpact: "Вплив на дохід",
    customers: "клієнтів",
    perWeek: "на тиждень",
    gameName: "Гра",
    customersCount: "Клієнти",
    treasureHuntOrigin: "Джерело квесту",
    guestsCount: "Гості",
    weekLabel: "Тиждень {n}",
    sourcesSubtitle: "Як клієнти знаходять ваш ресторан",
    funnelSubtitle: "Від входу до постійного клієнта",
    gamesSubtitle: "В які ігри найчастіше грають після відмітки",
    crossSubtitle: "Ресторани, чиї квести надсилають вам гостей",
    growthSubtitle: "Відстежуйте свою динаміку тиждень за тижнем",
    playCount: "гра",
    playsCount: "ігор",

    /* Tournament Mode */
    activeTournaments: "Активні турніри",
    liveTournaments: "Живі турніри",
    liveTournament: "Живий турнір",
    noActiveTournaments: "Зараз турнірів немає",
    tournamentEndsIn: "Закінчується через {n}",
    tournamentEnded: "Турнір завершено",
    playToWin: "Грай, щоб виграти",
    yourRank: "Твій рейтинг",
    winningPrize: "Ти виграєш: {prize}",
    myPrizes: "Мої призи",
    noPrizes: "Поки немає призів",
    claimCode: "Код: {code}",
    validUntil: "Дійсний до {time}",
    claimRedeemed: "Отримано",
    claimPending: "Очікує",
    expiresInHours: "Закінч. через {h}год",
    mins: "хв",
    claimExpired: "Прострочено",
    loadAll: "Завантажити все",
    tournamentWonTitle: "🎉 Переможець турніру!",
    tournamentWon: "Ти виграв {prize} у {venue}!",
    tournamentLost: "Майже! {winner} переміг з {score} очками.",
    rankGained: "Ти #{rank} — виграєш {prize}!",
    rankLost: "Ти опустився на #{rank}. Ще одна гра, щоб повернутися!",
    tournament: "Турнір",
    launchTournament: "Запустити турнір",
    prizeLabel: "Приз",
    topWinners: "Переможців",
    launch1hButton: "Запустити турнір на 3 години",
    tournamentActive: "Турнір активний",
    noActiveTournament: "Немає активного турніру",
    tournamentLeaderboard: "Таблиця турніру",
    yourPosition: "Твоя позиція",
    placeSuffix: {
      "1": "-ше",
      "2": "-ге",
      "3": "-тє"
    }
  }
};
